name: 'Add Reviewers'
on:
  pull_request_target:
    types: [opened, ready_for_review, edited, unassigned]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'