name: 'Lint'
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ./app
    - name: Run ESLint
      run: npm run lint
      working-directory: ./app