name: 'Lint and format'
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
    - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write ./src/**/*.{js,jsx,ts,tsx,json,css,scss}
    - name: Install modules
      run: npm install
      working-directory: ./app
    - name: Run ESLint
      run: npm run lint
      working-directory: ./app
