name: 'Lint'
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CD to App dir
      run: cd app/
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: eslint src/ --ext .js,.jsx,.ts,.tsx