name: 'Lint'
on: [pull_request]
env: 
  working-directory: ./app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: eslint src/ --ext .js,.jsx,.ts,.tsx