name: 'Lint and format'
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prettify code
      uses: creyD/prettier_action@v4.2
      with:
        prettier_options: --write ./src/**/*.{js,jsx,ts,tsx,json,css,scss}
    - name: Install modules
      run: npm install
      working-directory: ./app
    - name: Run ESLint
      run: npm run lint
      working-directory: ./app
